# Generated by Django 3.1.4 on 2021-02-03 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/image/%Y/%m/%d', verbose_name='제품 이미지')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.review')),
            ],
            options={
                'verbose_name': 'review_photo',
                'verbose_name_plural': 'review_photos',
                'ordering': ['review'],
            },
        ),
        migrations.CreateModel(
            name='Product_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='products/mainImage/%Y/%m/%d', verbose_name='메인 이미지')),
                ('sub_image', models.ImageField(upload_to='products/subImage/%Y/%m/%d', verbose_name='서브 이미지')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'ordering': ['product'],
            },
        ),
    ]
