# Generated by Django 3.1.4 on 2021-02-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykurly', '0003_auto_20210217_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성 일자'),
        ),
    ]
