# Generated by Django 3.1.4 on 2021-02-03 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=30, verbose_name='이메일')),
                ('person_name', models.CharField(max_length=20, verbose_name='성명')),
                ('age', models.IntegerField(editable=False, null=True, verbose_name='나이')),
                ('phone_number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('home_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='주소')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
