# Generated by Django 3.1.4 on 2021-02-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('product_image', models.ImageField(upload_to='reviews/image/%Y/%m/%d', verbose_name='제품 이미지')),
                ('views', models.PositiveIntegerField(verbose_name='조회수')),
                ('helps', models.PositiveIntegerField(verbose_name='도움이 돼요')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 일자')),
            ],
        ),
    ]
